# These are supported funding model platforms

ko_fi: "mohamedslimane"    # لدعم Ko-fi
buy_me_a_coffee: "oFjHPme"  # لدعم Buy Me a Coffee
liberapay: "MohamedSlimane"  # لدعم Liberapay
custom: ["https://paypal.me/MSDDEVER"]  # روابط مخصصة مثل PayPal
