# Generated by Django 4.2.6 on 2023-10-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Serial')),
                ('framework', models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('bottle', 'Bottle')], default='django', max_length=500, verbose_name='Framework')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('domain', models.CharField(max_length=50, unique=True, verbose_name='Domain')),
                ('port', models.IntegerField(unique=True, verbose_name='Port')),
                ('www_path', models.CharField(max_length=5000, verbose_name='Path')),
                ('uwsgi_path', models.CharField(help_text='The folder that contains the wsgi.py file, for example: (mayproject)', max_length=5000, verbose_name='Uwsgi path')),
                ('venv_path', models.CharField(max_length=5000, verbose_name='Environment Path')),
                ('nginx_config', models.CharField(max_length=5000, verbose_name='Nginx config')),
                ('uwsgi_config', models.CharField(max_length=5000, verbose_name='Uwsgi config')),
                ('force_https', models.BooleanField(default=False, verbose_name='Force HTTPS')),
                ('activated', models.BooleanField(default=True, verbose_name='Activated')),
            ],
        ),
        migrations.CreateModel(
            name='MysqlDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Serial')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Name')),
                ('username', models.CharField(max_length=500, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Key')),
                ('value', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='PostgresDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Serial')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Name')),
                ('username', models.CharField(max_length=500, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='AppCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Serial')),
                ('domain', models.CharField(max_length=50, verbose_name='Domain')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_app', to='dpanel.app', verbose_name='App')),
            ],
        ),
    ]
