# Generated by Django 4.2.6 on 2023-10-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcertificate',
            name='domain',
            field=models.CharField(default='', max_length=50, verbose_name='Domain'),
            preserve_default=False,
        ),
    ]
