# Generated by Django 4.1.7 on 2023-04-01 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpanel', '0003_mysqldatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Serial')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField()),
                ('app', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='dpanel.app', unique=True, verbose_name='App')),
            ],
        ),
    ]
