# Generated by Django 4.1.7 on 2023-04-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpanel', '0004_appcertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcertificate',
            name='expire_date',
        ),
        migrations.AlterField(
            model_name='appcertificate',
            name='app',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_app', to='dpanel.app', unique=True, verbose_name='App'),
        ),
    ]
