# Generated by Django 4.1.7 on 2023-04-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpanel', '0005_remove_appcertificate_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcertificate',
            name='app',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_app', to='dpanel.app', verbose_name='App'),
        ),
    ]
