# Generated by Django 4.1.7 on 2023-04-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpanel', '0006_alter_appcertificate_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcertificate',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_app', to='dpanel.app', verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='appcertificate',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
