# Generated by Django 4.2.6 on 2023-10-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpanel', '0007_alter_appcertificate_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Key')),
                ('value', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Value')),
            ],
        ),
    ]
